/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebankingsystemcwk;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class SelectCustmerPage extends javax.swing.JFrame {

    /**
     * Creates new form SelectCustmerPage
     */
    public SelectCustmerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accNumberTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cusNameTxt = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jLabel2.setFont(new java.awt.Font("AvenirNext LT Pro Bold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HIGH STREET BANK");

        jLabel3.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account Number");

        searchBtn.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        searchBtn.setText("?");
        searchBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Name");

        submit.setFont(new java.awt.Font("Gotham Bold", 0, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Gotham Bold", 0, 18)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("* Press verify button [?} to verify account number");

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOTE : You can't edit your ACCOUNT NUMBER and your NAME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(submit)
                        .addGap(85, 85, 85)
                        .addComponent(cancelBtn)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accNumberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(cusNameTxt))
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(submit))
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      submit.setEnabled(false);
      cusNameTxt.setEditable(false);
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * 
     * @param evt 
     */
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       String cusName=cusNameTxt.getText();
       String accNumber=accNumberTxt.getText();
       
       AddCustomerUI customer=new AddCustomerUI();
       customer.setCusName(cusName);
       customer.setAccNumber(accNumber);
       customer.setVisible(true);
       cusNameTxt.setEditable(false);
       accNumberTxt.setEditable(false);
        try {
            //connection
            //Connection con = getConnection();
            //execute sql query
            //PreparedStatement pst = con.prepareStatement("Select birthdate,address,mobile,email,accountType,accountNumber,sortCode,balance,card from customer where accountNumber='" + accNumber + "'");

            //ResultSet rs = pst.executeQuery();
            ArrayList<String> selectedCus=new ArrayList<String>();
            selectedCus=(ArrayList<String>) selectCustomer(accNumber);
            String tempString = "";
            if (selectedCus.size()==1) {
                tempString = selectedCus.get(0);
                String[] splitArr = tempString.split(" "); // caution : can't put full name
                // because splits with single space
                // likewise, can't have space seperated values IN SINGLE FIELD
                // to modify, you should modify the return string in the method (in server)
                
                customer.setBirthdate(splitArr[0]);
                customer.setAddress(splitArr[1]);
                customer.setMobileNo(splitArr[2]);
                customer.setEmail(splitArr[3]);
                customer.setAccountType(splitArr[4]);
                customer.setSortCode(splitArr[5]);
                customer.setBalance(splitArr[6]);
                customer.setCard(splitArr[7]);
                
     
                
                customer.changeStateOfTextFields(false);
               //customer.setEnabled(false);
               customer.changeStateOfButton(false);
               customer.changeStateOfEditDeleteBtn(true);
            } else {
               
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
       //Controller.addCustomer(cusName, cusName, cusName, cusName, cusName, accNumber, accNumber, cusName, ALLBITS, cusName);
    }//GEN-LAST:event_submitActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            String accNumber = accNumberTxt.getText();
            String cusName = " ";
            cusName=verifyCustomer(accNumber);
            if (checkAccountNumberField(accNumber) == true) {
                if (validateCustomer(accNumber, cusName) == true) {
                   // Connection con;
                    try {
                        
//                        con = getConnection();
//                        //execute sql query
//                        PreparedStatement pst = con.prepareStatement("Select cusName from customer where accountNumber='" + accNumber + "'");
//                        ResultSet rs = pst.executeQuery();
//                        if (rs.next()) {
                            cusNameTxt.setText(cusName);
                            cusNameTxt.setEditable(false);
                            submit.setEnabled(true);
                      //  }
                    } catch (Exception ex) {
                        
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Account Number does not existing.Plz check","ERROR",JOptionPane.ERROR_MESSAGE);
                    accNumberTxt.setText(" ");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Please fill account number field","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex,"Error",JOptionPane.ERROR_MESSAGE);
            accNumberTxt.setText(" ");
        }


    }//GEN-LAST:event_searchBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        CustomerListPage cusList=new CustomerListPage();
        setVisible(false);
        cusList.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SelectCustmerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SelectCustmerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SelectCustmerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SelectCustmerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SelectCustmerPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNumberTxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cusNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<java.lang.String> selectCustomer(java.lang.String accNumber) {
        ebankingsystemCustomer.EBankingCustomerWs_Service service = new ebankingsystemCustomer.EBankingCustomerWs_Service();
        ebankingsystemCustomer.EBankingCustomerWs port = service.getEBankingCustomerWsPort();
        return port.selectCustomer(accNumber);
    }

    private static String verifyCustomer(java.lang.String accountNumber) {
        ebankingsystemCustomer.EBankingCustomerWs_Service service = new ebankingsystemCustomer.EBankingCustomerWs_Service();
        ebankingsystemCustomer.EBankingCustomerWs port = service.getEBankingCustomerWsPort();
        return port.verifyCustomer(accountNumber);
    }

    private static boolean validateCustomer(java.lang.String accountNumber, java.lang.String cusName) {
        ebankingsystemCustomer.EBankingCustomerWs_Service service = new ebankingsystemCustomer.EBankingCustomerWs_Service();
        ebankingsystemCustomer.EBankingCustomerWs port = service.getEBankingCustomerWsPort();
        return port.validateCustomer(accountNumber, cusName);
    }

    private static boolean checkAccountNumberField(java.lang.String accountNumber) {
        ebankingsystemCustomer.EBankingCustomerWs_Service service = new ebankingsystemCustomer.EBankingCustomerWs_Service();
        ebankingsystemCustomer.EBankingCustomerWs port = service.getEBankingCustomerWsPort();
        return port.checkAccountNumberField(accountNumber);
    }

  
}
